FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python3", "ping-instrumented.py"] 
# use ping-otel-simple.py or ping-instrumented.py as needed